rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  # - rbx-2.0
  # - jruby

env:
  - GEM=sunspot
  - GEM=sunspot_rails RAILS=2.3.16
  - GEM=sunspot_rails RAILS=3.0.20
  - GEM=sunspot_rails RAILS=3.1.10
  - GEM=sunspot_rails RAILS=3.2.11

# Limit the size of the matrix by only performing one build against
# 1.8.7 and 1.9.2
matrix:
  exclude:
    - rvm: 1.8.7
      env: GEM=sunspot_rails RAILS=3.0.20
    - rvm: 1.8.7
      env: GEM=sunspot_rails RAILS=3.1.10
    - rvm: 1.8.7
      env: GEM=sunspot_rails RAILS=3.2.11
    - rvm: 1.9.3
      env: GEM=sunspot_rails RAILS=2.3.16

  allow_failures:
    - rvm: 2.0.0


script:
  - ci/travis.sh
